copy /Y puzzle.* ..\03
copy /Y puzzle.* ..\05
copy /Y puzzle.* ..\06
copy /Y puzzle.* ..\07
copy /Y puzzle.* ..\08
copy /Y puzzle.* ..\09
copy /Y puzzle.* ..\10
copy /Y puzzle.* ..\11
copy /Y puzzle.* ..\12
copy /Y puzzle.* ..\13
copy /Y puzzle.* ..\14
copy /Y puzzle.* ..\15
copy /Y puzzle.* ..\16
copy /Y puzzle.* ..\17
copy /Y puzzle.* ..\18
copy /Y puzzle.* ..\19
copy /Y puzzle.* ..\20
copy /Y puzzle.* ..\21
copy /Y puzzle.* ..\22
copy /Y puzzle.* ..\23
copy /Y puzzle.* ..\24
copy /Y puzzle.* ..\25
